Feature/one file pr scenario #000
aau-network-security/defatt pull request #97
Opened 2021-12-01 15:27 UTC by Lanestolen

2021-12-05 16:25 UTC, rasmim approved these changes

2021-12-05 17:03 UTC, rasmim commented on scripts/clean.sh
> +sudo ip link del ${bridge}_vlan30 mode
```
sudo ip link del ${bridge}_vlan10
sudo ip link del ${bridge}_vlan20
sudo ip link del ${bridge}_vlan30

```

2021-12-05 17:04 UTC, rasmim commented on scripts/clean.sh
> +sudo ip link del ${bridge}_vlan30 mode
it is working without the `mode` keyword at the end.

2021-12-05 17:04 UTC, rasmim requested changes
clean script. small update

2021-12-05 18:15 UTC, rasmim commented
I tried to run it on a development server. I got this error: 

```
7:13PM ERR mirroring traffic error="exit status 1: ovs-vsctl: select_vlan=: argument does not end in \"=\" followed by a value."
7:13PM ERR configuring monitoring error="exit status 1: ovs-vsctl: select_vlan=: argument does not end in \"=\" followed by a value."
```

Can you please investigate @Lanestolen ?

2021-12-07 16:11 UTC, Lanestolen commented
Can you send me the scenario file used during this test?

2021-12-09 10:05 UTC, rasmim commented
I checked another time, it is no problem with the pull request. I was my mistake, using a scenario number that was not existing. 

`DEFAT_SSL_OFF=true DEFAT_PORT=5554 go run app/client/main.go start -n "dnst" -t "dnst" -s 1`


It can be merged, I will be nice to have a panic if the scenario number does not exist.

2021-12-09 11:47 UTC, rasmim approved these changes

2021-12-11 20:05 UTC, rasmim approved these changes

2021-12-11 20:06 UTC, rasmim commented
Please proceed with merge :)

2021-12-11 22:33 UTC, merged